### PR TITLE
Add menu ordering

### PR DESCRIPTION
**Pull request by nspinazz89**
adds menu ordering functionality for main sidebar.

### CODE REVIEW

**Review by cnorm35 — APPROVED** [review]
nicely done!  this looks good except for the small nit ⛏ on indentation

**Comment by nspinazz89** [comment]
ah good point @cnorm35 got it

**Review by jacobherrington — APPROVED** [review]
‼️

**Review by fastjames — APPROVED** [review]
Looks good to me. :cake:

**Pull request merged**
