### PR TITLE
Add ordering menu items

### PR DESCRIPTION
**Pull request by jacobherrington**
Round 2 of #4

### CODE REVIEW

**Comment by fastjames** [comment]
This needs to be PRed against `gemini_master_v271`. We don't use `gemini_master` right now.

**Comment by fastjames** [comment]
I tried changing the base myself and it seemed to introduce a lot of other commits. I think these commits will need to be applied against a new branch of `gemini_master_v271`.

**Review by fastjames — CHANGES_REQUESTED** [review]
Needs to be rebased against the currently used branch.

**Comment by fastjames** [comment]
Wait has this been superseded by https://github.com/geminimvp/solidus/pull/6 ?

**Comment by fastjames** [comment]
Superseded.

**Comment by jacobherrington** [comment]
Yes, I made this to send Spinazze with the intention that he would finish it up. Ended up happening in #6. 👍

**Pull request closed without merging**
